services:
  relics_docker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - $HOME:/root
    ports:
      - xxxx:22 #should be changed to the port you want to use for ssh
    logging: 
      driver: "json-file"
      options: 
        max-size: 1m
        max-file: 1
