/gps/particle gamma

/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1
/gps/pos/centre 62.5 0 0 cm
/gps/pos/halfx 125 cm
/gps/pos/halfy 125 cm

/gps/ang/type iso
/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 90 deg

/gps/ene/type Arb
/gps/ene/diffspec 1
/gps/hist/type arb

/control/getEnv GAMMAHIST
#/control/echo {GAMMAHIST}
/gps/hist/file {GAMMAHIST}
/gps/hist/inter Lin
