/gps/particle neutron

/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1
/gps/pos/centre 7.9 0 0 m
/gps/pos/halfx 1.52 m
/gps/pos/halfy 2.1335 m

/gps/ang/type beam1d
/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1
/gps/ang/sigma_r 0.0848703 rad

/gps/ene/type Arb
/gps/ene/diffspec 1
/gps/hist/type arb

/control/getEnv NEUTRONHIST
#/control/echo {NEUTRONHIST}
/gps/hist/file {NEUTRONHIST}
/gps/hist/inter Lin
