/gps/particle neutron

/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0
/gps/pos/centre 25 0 0 m
/gps/pos/radius 1.52 m
/gps/pos/halfz 2.1335 m

/gps/ang/type iso
/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1
/gps/ang/mintheta 0 rad
/gps/ang/maxtheta 0.2003348423 rad

/gps/ene/type Arb
/gps/ene/diffspec 1
/gps/hist/type arb

/control/getEnv NEUTRONHIST
#/control/echo {NEUTRONHIST}
/gps/hist/file {NEUTRONHIST}
/gps/hist/inter Lin
