message("enable relics")
set(source_path ${PROJECT_SOURCE_DIR}/user/detectors/relics)
set(Detector ${Detector} ${source_path}/Material.cc)
set(Detector ${Detector} ${source_path}/Monoblock.cc)
set(Detector ${Detector} ${source_path}/Cuboid.cc)
set(Detector ${Detector} ${source_path}/Cylinder.cc)
set(Detector ${Detector} ${source_path}/Prism.cc)
set(Detector ${Detector} ${source_path}/Polyhedra.cc)
set(Detector ${Detector} ${source_path}/HolesBoard.cc)
set(Detector ${Detector} ${source_path}/HollowCuboid.cc)
set(Detector ${Detector} ${source_path}/MeshGrid.cc)
set(Detector ${Detector} ${source_path}/MeshGrid_cuowei.cc)
set(Detector ${Detector} ${source_path}/World.cc)
set(Detector ${Detector} ${source_path}/PMTsR8520.cc)
set(Detector ${Detector} ${source_path}/Array.cc)
set(Detector ${Detector} ${source_path}/GetMass.cc)
set(Detector ${Detector} ${source_path}/Tube.cc)
configure_file("${CMAKE_SOURCE_DIR}/data/botPMT.txt" "${CMAKE_BINARY_DIR}/data/botPMT.txt" COPYONLY)
configure_file("${CMAKE_SOURCE_DIR}/data/topPMT.txt" "${CMAKE_BINARY_DIR}/data/topPMT.txt" COPYONLY)
configure_file("${CMAKE_SOURCE_DIR}/data/topTeflon.txt" "${CMAKE_BINARY_DIR}/data/topTeflon.txt" COPYONLY)
configure_file("${CMAKE_SOURCE_DIR}/data/botTeflon.txt" "${CMAKE_BINARY_DIR}/data/botTeflon.txt" COPYONLY)
# configure_file("${CMAKE_SOURCE_DIR}/data/observation_holes.txt" "${CMAKE_BINARY_DIR}/data/observation_holes.txt" COPYONLY)
configure_file("${CMAKE_SOURCE_DIR}/data/shaping_rings.txt" "${CMAKE_BINARY_DIR}/data/shaping_rings.txt" COPYONLY)
configure_file("${CMAKE_SOURCE_DIR}/data/Pipe.txt" "${CMAKE_BINARY_DIR}/data/Pipe.txt" COPYONLY)
configure_file("${CMAKE_SOURCE_DIR}/data/Flange.txt" "${CMAKE_BINARY_DIR}/data/Flange.txt" COPYONLY)
configure_file("${CMAKE_SOURCE_DIR}/data/gammaON.txt" "${CMAKE_BINARY_DIR}/data/gammaON.txt" COPYONLY)
configure_file("${CMAKE_SOURCE_DIR}/data/neutronA.txt" "${CMAKE_BINARY_DIR}/data/neutronA.txt" COPYONLY)
configure_file("${CMAKE_SOURCE_DIR}/data/neutronE.txt" "${CMAKE_BINARY_DIR}/data/neutronE.txt" COPYONLY)
configure_file("${CMAKE_SOURCE_DIR}/data/neutronOFF.txt" "${CMAKE_BINARY_DIR}/data/neutronOFF.txt" COPYONLY)
configure_file("${CMAKE_SOURCE_DIR}/data/neutronON.txt" "${CMAKE_BINARY_DIR}/data/neutronON.txt" COPYONLY)



